name: Coverage

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  REDIS5_HOST: localhost
  REDIS6_HOST: localhost
  POSTGRES_HOST: localhost
  WEB_SERVICE_HOST: http://localhost:3030

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start services
        run: make start-services

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          extensions: tokenizer
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --prefer-stable --optimize-autoloader --quiet

      - name: Generate the coverage report
        run: vendor/bin/tester -p phpdbg -C -s --coverage ./coverage.xml --coverage-src ./src ./tests

      - name: Upload the coverage report
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar
          php php-coveralls.phar --verbose --config tests/.coveralls.yml
